arch: s390x
services:
  - docker
script: 
    docker build -t zmicroservicesdvmz -f Dockerfile .
before_deploy:
    - docker tag  zmicroservicesdvmz  "$DOCKER_USERNAME"/zmicroservicesdvmz:latest
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
deploy:
  provider: script
  script: 
     docker push "$DOCKER_USERNAME"/zmicroservicesdvmz:latest
  on:
    branch: master  